# Generated by Django 5.2.14 on 2026-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome класс, например 'fas fa-code'", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
